### ISSUE TITLE
Don't use personal GitHub tokens

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/notification-pr-bot#4]
On the admin and API repositories we currently use personal GitHub tokens to authenticate with the API.

This is not very robust as people come and go.

Look for another auth mechanism, maybe GitHub Apps?

**Comment by Moro-Code** [comment]
related 
https://github.com/cds-snc/notification-api/pull/1315
https://github.com/cds-snc/notification-admin/pull/1074
https://github.com/cds-snc/notification-document-download-api/pull/42
https://github.com/cds-snc/notification-document-download-frontend/pull/59
https://github.com/cds-snc/notification-documentation/pull/84
